################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/poller/ndef_poller.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/poller/ndef_poller_message.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/poller/ndef_poller_rf.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/poller/ndef_t2t.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/poller/ndef_t3t.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/poller/ndef_t4t.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/poller/ndef_t5t.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/poller/ndef_t5t_rf.c 

C_DEPS += \
./Middlewares/ndef/poller/ndef_poller.d \
./Middlewares/ndef/poller/ndef_poller_message.d \
./Middlewares/ndef/poller/ndef_poller_rf.d \
./Middlewares/ndef/poller/ndef_t2t.d \
./Middlewares/ndef/poller/ndef_t3t.d \
./Middlewares/ndef/poller/ndef_t4t.d \
./Middlewares/ndef/poller/ndef_t5t.d \
./Middlewares/ndef/poller/ndef_t5t_rf.d 

OBJS += \
./Middlewares/ndef/poller/ndef_poller.o \
./Middlewares/ndef/poller/ndef_poller_message.o \
./Middlewares/ndef/poller/ndef_poller_rf.o \
./Middlewares/ndef/poller/ndef_t2t.o \
./Middlewares/ndef/poller/ndef_t3t.o \
./Middlewares/ndef/poller/ndef_t4t.o \
./Middlewares/ndef/poller/ndef_t5t.o \
./Middlewares/ndef/poller/ndef_t5t_rf.o 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/ndef/poller/ndef_poller.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/poller/ndef_poller.c Middlewares/ndef/poller/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/poller/ndef_poller_message.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/poller/ndef_poller_message.c Middlewares/ndef/poller/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/poller/ndef_poller_rf.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/poller/ndef_poller_rf.c Middlewares/ndef/poller/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/poller/ndef_t2t.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/poller/ndef_t2t.c Middlewares/ndef/poller/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/poller/ndef_t3t.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/poller/ndef_t3t.c Middlewares/ndef/poller/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/poller/ndef_t4t.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/poller/ndef_t4t.c Middlewares/ndef/poller/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/poller/ndef_t5t.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/poller/ndef_t5t.c Middlewares/ndef/poller/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/poller/ndef_t5t_rf.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/poller/ndef_t5t_rf.c Middlewares/ndef/poller/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-ndef-2f-poller

clean-Middlewares-2f-ndef-2f-poller:
	-$(RM) ./Middlewares/ndef/poller/ndef_poller.cyclo ./Middlewares/ndef/poller/ndef_poller.d ./Middlewares/ndef/poller/ndef_poller.o ./Middlewares/ndef/poller/ndef_poller.su ./Middlewares/ndef/poller/ndef_poller_message.cyclo ./Middlewares/ndef/poller/ndef_poller_message.d ./Middlewares/ndef/poller/ndef_poller_message.o ./Middlewares/ndef/poller/ndef_poller_message.su ./Middlewares/ndef/poller/ndef_poller_rf.cyclo ./Middlewares/ndef/poller/ndef_poller_rf.d ./Middlewares/ndef/poller/ndef_poller_rf.o ./Middlewares/ndef/poller/ndef_poller_rf.su ./Middlewares/ndef/poller/ndef_t2t.cyclo ./Middlewares/ndef/poller/ndef_t2t.d ./Middlewares/ndef/poller/ndef_t2t.o ./Middlewares/ndef/poller/ndef_t2t.su ./Middlewares/ndef/poller/ndef_t3t.cyclo ./Middlewares/ndef/poller/ndef_t3t.d ./Middlewares/ndef/poller/ndef_t3t.o ./Middlewares/ndef/poller/ndef_t3t.su ./Middlewares/ndef/poller/ndef_t4t.cyclo ./Middlewares/ndef/poller/ndef_t4t.d ./Middlewares/ndef/poller/ndef_t4t.o ./Middlewares/ndef/poller/ndef_t4t.su ./Middlewares/ndef/poller/ndef_t5t.cyclo ./Middlewares/ndef/poller/ndef_t5t.d ./Middlewares/ndef/poller/ndef_t5t.o ./Middlewares/ndef/poller/ndef_t5t.su ./Middlewares/ndef/poller/ndef_t5t_rf.cyclo ./Middlewares/ndef/poller/ndef_t5t_rf.d ./Middlewares/ndef/poller/ndef_t5t_rf.o ./Middlewares/ndef/poller/ndef_t5t_rf.su

.PHONY: clean-Middlewares-2f-ndef-2f-poller

