################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_message.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_record.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_aar.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_bluetooth.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_deviceinfo.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_empty.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_flat.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_media.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_text.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_tnep.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_uri.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_vcard.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_wifi.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_wlc.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_wpcwlc.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_types.c 

C_DEPS += \
./Middlewares/ndef/message/ndef_message.d \
./Middlewares/ndef/message/ndef_record.d \
./Middlewares/ndef/message/ndef_type_aar.d \
./Middlewares/ndef/message/ndef_type_bluetooth.d \
./Middlewares/ndef/message/ndef_type_deviceinfo.d \
./Middlewares/ndef/message/ndef_type_empty.d \
./Middlewares/ndef/message/ndef_type_flat.d \
./Middlewares/ndef/message/ndef_type_media.d \
./Middlewares/ndef/message/ndef_type_text.d \
./Middlewares/ndef/message/ndef_type_tnep.d \
./Middlewares/ndef/message/ndef_type_uri.d \
./Middlewares/ndef/message/ndef_type_vcard.d \
./Middlewares/ndef/message/ndef_type_wifi.d \
./Middlewares/ndef/message/ndef_type_wlc.d \
./Middlewares/ndef/message/ndef_type_wpcwlc.d \
./Middlewares/ndef/message/ndef_types.d 

OBJS += \
./Middlewares/ndef/message/ndef_message.o \
./Middlewares/ndef/message/ndef_record.o \
./Middlewares/ndef/message/ndef_type_aar.o \
./Middlewares/ndef/message/ndef_type_bluetooth.o \
./Middlewares/ndef/message/ndef_type_deviceinfo.o \
./Middlewares/ndef/message/ndef_type_empty.o \
./Middlewares/ndef/message/ndef_type_flat.o \
./Middlewares/ndef/message/ndef_type_media.o \
./Middlewares/ndef/message/ndef_type_text.o \
./Middlewares/ndef/message/ndef_type_tnep.o \
./Middlewares/ndef/message/ndef_type_uri.o \
./Middlewares/ndef/message/ndef_type_vcard.o \
./Middlewares/ndef/message/ndef_type_wifi.o \
./Middlewares/ndef/message/ndef_type_wlc.o \
./Middlewares/ndef/message/ndef_type_wpcwlc.o \
./Middlewares/ndef/message/ndef_types.o 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/ndef/message/ndef_message.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_message.c Middlewares/ndef/message/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/message/ndef_record.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_record.c Middlewares/ndef/message/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/message/ndef_type_aar.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_aar.c Middlewares/ndef/message/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/message/ndef_type_bluetooth.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_bluetooth.c Middlewares/ndef/message/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/message/ndef_type_deviceinfo.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_deviceinfo.c Middlewares/ndef/message/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/message/ndef_type_empty.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_empty.c Middlewares/ndef/message/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/message/ndef_type_flat.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_flat.c Middlewares/ndef/message/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/message/ndef_type_media.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_media.c Middlewares/ndef/message/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/message/ndef_type_text.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_text.c Middlewares/ndef/message/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/message/ndef_type_tnep.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_tnep.c Middlewares/ndef/message/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/message/ndef_type_uri.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_uri.c Middlewares/ndef/message/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/message/ndef_type_vcard.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_vcard.c Middlewares/ndef/message/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/message/ndef_type_wifi.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_wifi.c Middlewares/ndef/message/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/message/ndef_type_wlc.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_wlc.c Middlewares/ndef/message/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/message/ndef_type_wpcwlc.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_type_wpcwlc.c Middlewares/ndef/message/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ndef/message/ndef_types.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/ndef/Src/message/ndef_types.c Middlewares/ndef/message/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-ndef-2f-message

clean-Middlewares-2f-ndef-2f-message:
	-$(RM) ./Middlewares/ndef/message/ndef_message.cyclo ./Middlewares/ndef/message/ndef_message.d ./Middlewares/ndef/message/ndef_message.o ./Middlewares/ndef/message/ndef_message.su ./Middlewares/ndef/message/ndef_record.cyclo ./Middlewares/ndef/message/ndef_record.d ./Middlewares/ndef/message/ndef_record.o ./Middlewares/ndef/message/ndef_record.su ./Middlewares/ndef/message/ndef_type_aar.cyclo ./Middlewares/ndef/message/ndef_type_aar.d ./Middlewares/ndef/message/ndef_type_aar.o ./Middlewares/ndef/message/ndef_type_aar.su ./Middlewares/ndef/message/ndef_type_bluetooth.cyclo ./Middlewares/ndef/message/ndef_type_bluetooth.d ./Middlewares/ndef/message/ndef_type_bluetooth.o ./Middlewares/ndef/message/ndef_type_bluetooth.su ./Middlewares/ndef/message/ndef_type_deviceinfo.cyclo ./Middlewares/ndef/message/ndef_type_deviceinfo.d ./Middlewares/ndef/message/ndef_type_deviceinfo.o ./Middlewares/ndef/message/ndef_type_deviceinfo.su ./Middlewares/ndef/message/ndef_type_empty.cyclo ./Middlewares/ndef/message/ndef_type_empty.d ./Middlewares/ndef/message/ndef_type_empty.o ./Middlewares/ndef/message/ndef_type_empty.su ./Middlewares/ndef/message/ndef_type_flat.cyclo ./Middlewares/ndef/message/ndef_type_flat.d ./Middlewares/ndef/message/ndef_type_flat.o ./Middlewares/ndef/message/ndef_type_flat.su ./Middlewares/ndef/message/ndef_type_media.cyclo ./Middlewares/ndef/message/ndef_type_media.d ./Middlewares/ndef/message/ndef_type_media.o ./Middlewares/ndef/message/ndef_type_media.su ./Middlewares/ndef/message/ndef_type_text.cyclo ./Middlewares/ndef/message/ndef_type_text.d ./Middlewares/ndef/message/ndef_type_text.o ./Middlewares/ndef/message/ndef_type_text.su ./Middlewares/ndef/message/ndef_type_tnep.cyclo ./Middlewares/ndef/message/ndef_type_tnep.d ./Middlewares/ndef/message/ndef_type_tnep.o ./Middlewares/ndef/message/ndef_type_tnep.su ./Middlewares/ndef/message/ndef_type_uri.cyclo ./Middlewares/ndef/message/ndef_type_uri.d ./Middlewares/ndef/message/ndef_type_uri.o ./Middlewares/ndef/message/ndef_type_uri.su ./Middlewares/ndef/message/ndef_type_vcard.cyclo ./Middlewares/ndef/message/ndef_type_vcard.d ./Middlewares/ndef/message/ndef_type_vcard.o ./Middlewares/ndef/message/ndef_type_vcard.su ./Middlewares/ndef/message/ndef_type_wifi.cyclo ./Middlewares/ndef/message/ndef_type_wifi.d ./Middlewares/ndef/message/ndef_type_wifi.o ./Middlewares/ndef/message/ndef_type_wifi.su ./Middlewares/ndef/message/ndef_type_wlc.cyclo ./Middlewares/ndef/message/ndef_type_wlc.d ./Middlewares/ndef/message/ndef_type_wlc.o ./Middlewares/ndef/message/ndef_type_wlc.su ./Middlewares/ndef/message/ndef_type_wpcwlc.cyclo ./Middlewares/ndef/message/ndef_type_wpcwlc.d ./Middlewares/ndef/message/ndef_type_wpcwlc.o ./Middlewares/ndef/message/ndef_type_wpcwlc.su ./Middlewares/ndef/message/ndef_types.cyclo ./Middlewares/ndef/message/ndef_types.d ./Middlewares/ndef/message/ndef_types.o ./Middlewares/ndef/message/ndef_types.su

.PHONY: clean-Middlewares-2f-ndef-2f-message

