################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/app_freertos.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/crc.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/custom_bus.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/dcache.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/dma2d.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/gpdma.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/gpio.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/gpu2d.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/hspi.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/i2c.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/icache.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/jpeg.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/ltdc.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/main.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/spi.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/stm32u5xx_hal_msp.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/stm32u5xx_hal_timebase_tim.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/stm32u5xx_it.c \
../Application/User/Core/syscalls.c \
../Application/User/Core/sysmem.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/usart.c 

C_DEPS += \
./Application/User/Core/app_freertos.d \
./Application/User/Core/crc.d \
./Application/User/Core/custom_bus.d \
./Application/User/Core/dcache.d \
./Application/User/Core/dma2d.d \
./Application/User/Core/gpdma.d \
./Application/User/Core/gpio.d \
./Application/User/Core/gpu2d.d \
./Application/User/Core/hspi.d \
./Application/User/Core/i2c.d \
./Application/User/Core/icache.d \
./Application/User/Core/jpeg.d \
./Application/User/Core/ltdc.d \
./Application/User/Core/main.d \
./Application/User/Core/spi.d \
./Application/User/Core/stm32u5xx_hal_msp.d \
./Application/User/Core/stm32u5xx_hal_timebase_tim.d \
./Application/User/Core/stm32u5xx_it.d \
./Application/User/Core/syscalls.d \
./Application/User/Core/sysmem.d \
./Application/User/Core/usart.d 

OBJS += \
./Application/User/Core/app_freertos.o \
./Application/User/Core/crc.o \
./Application/User/Core/custom_bus.o \
./Application/User/Core/dcache.o \
./Application/User/Core/dma2d.o \
./Application/User/Core/gpdma.o \
./Application/User/Core/gpio.o \
./Application/User/Core/gpu2d.o \
./Application/User/Core/hspi.o \
./Application/User/Core/i2c.o \
./Application/User/Core/icache.o \
./Application/User/Core/jpeg.o \
./Application/User/Core/ltdc.o \
./Application/User/Core/main.o \
./Application/User/Core/spi.o \
./Application/User/Core/stm32u5xx_hal_msp.o \
./Application/User/Core/stm32u5xx_hal_timebase_tim.o \
./Application/User/Core/stm32u5xx_it.o \
./Application/User/Core/syscalls.o \
./Application/User/Core/sysmem.o \
./Application/User/Core/usart.o 


# Each subdirectory must supply rules for building sources it contributes
Application/User/Core/app_freertos.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/app_freertos.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/crc.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/crc.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/custom_bus.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/custom_bus.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/dcache.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/dcache.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/dma2d.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/dma2d.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/gpdma.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/gpdma.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/gpio.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/gpio.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/gpu2d.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/gpu2d.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/hspi.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/hspi.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/i2c.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/i2c.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/icache.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/icache.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/jpeg.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/jpeg.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/ltdc.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/ltdc.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/main.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/main.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/spi.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/spi.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/stm32u5xx_hal_msp.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/stm32u5xx_hal_msp.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/stm32u5xx_hal_timebase_tim.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/stm32u5xx_hal_timebase_tim.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/stm32u5xx_it.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/stm32u5xx_it.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/%.o Application/User/Core/%.su Application/User/Core/%.cyclo: ../Application/User/Core/%.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/usart.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Core/Src/usart.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Application-2f-User-2f-Core

clean-Application-2f-User-2f-Core:
	-$(RM) ./Application/User/Core/app_freertos.cyclo ./Application/User/Core/app_freertos.d ./Application/User/Core/app_freertos.o ./Application/User/Core/app_freertos.su ./Application/User/Core/crc.cyclo ./Application/User/Core/crc.d ./Application/User/Core/crc.o ./Application/User/Core/crc.su ./Application/User/Core/custom_bus.cyclo ./Application/User/Core/custom_bus.d ./Application/User/Core/custom_bus.o ./Application/User/Core/custom_bus.su ./Application/User/Core/dcache.cyclo ./Application/User/Core/dcache.d ./Application/User/Core/dcache.o ./Application/User/Core/dcache.su ./Application/User/Core/dma2d.cyclo ./Application/User/Core/dma2d.d ./Application/User/Core/dma2d.o ./Application/User/Core/dma2d.su ./Application/User/Core/gpdma.cyclo ./Application/User/Core/gpdma.d ./Application/User/Core/gpdma.o ./Application/User/Core/gpdma.su ./Application/User/Core/gpio.cyclo ./Application/User/Core/gpio.d ./Application/User/Core/gpio.o ./Application/User/Core/gpio.su ./Application/User/Core/gpu2d.cyclo ./Application/User/Core/gpu2d.d ./Application/User/Core/gpu2d.o ./Application/User/Core/gpu2d.su ./Application/User/Core/hspi.cyclo ./Application/User/Core/hspi.d ./Application/User/Core/hspi.o ./Application/User/Core/hspi.su ./Application/User/Core/i2c.cyclo ./Application/User/Core/i2c.d ./Application/User/Core/i2c.o ./Application/User/Core/i2c.su ./Application/User/Core/icache.cyclo ./Application/User/Core/icache.d ./Application/User/Core/icache.o ./Application/User/Core/icache.su ./Application/User/Core/jpeg.cyclo ./Application/User/Core/jpeg.d ./Application/User/Core/jpeg.o ./Application/User/Core/jpeg.su ./Application/User/Core/ltdc.cyclo ./Application/User/Core/ltdc.d ./Application/User/Core/ltdc.o ./Application/User/Core/ltdc.su ./Application/User/Core/main.cyclo ./Application/User/Core/main.d ./Application/User/Core/main.o ./Application/User/Core/main.su ./Application/User/Core/spi.cyclo ./Application/User/Core/spi.d ./Application/User/Core/spi.o ./Application/User/Core/spi.su ./Application/User/Core/stm32u5xx_hal_msp.cyclo ./Application/User/Core/stm32u5xx_hal_msp.d ./Application/User/Core/stm32u5xx_hal_msp.o ./Application/User/Core/stm32u5xx_hal_msp.su ./Application/User/Core/stm32u5xx_hal_timebase_tim.cyclo ./Application/User/Core/stm32u5xx_hal_timebase_tim.d ./Application/User/Core/stm32u5xx_hal_timebase_tim.o ./Application/User/Core/stm32u5xx_hal_timebase_tim.su ./Application/User/Core/stm32u5xx_it.cyclo ./Application/User/Core/stm32u5xx_it.d ./Application/User/Core/stm32u5xx_it.o ./Application/User/Core/stm32u5xx_it.su ./Application/User/Core/syscalls.cyclo ./Application/User/Core/syscalls.d ./Application/User/Core/syscalls.o ./Application/User/Core/syscalls.su ./Application/User/Core/sysmem.cyclo ./Application/User/Core/sysmem.d ./Application/User/Core/sysmem.o ./Application/User/Core/sysmem.su ./Application/User/Core/usart.cyclo ./Application/User/Core/usart.d ./Application/User/Core/usart.o ./Application/User/Core/usart.su

.PHONY: clean-Application-2f-User-2f-Core

