################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_analogConfig.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_cd.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_crc.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_dpo.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_iso15693_2.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_isoDep.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_nfc.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_nfcDep.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_nfca.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_nfcb.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_nfcf.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_nfcv.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_st25tb.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_st25xv.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_t1t.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_t2t.c \
C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_t4t.c 

C_DEPS += \
./Middlewares/rfal/rfal_analogConfig.d \
./Middlewares/rfal/rfal_cd.d \
./Middlewares/rfal/rfal_crc.d \
./Middlewares/rfal/rfal_dpo.d \
./Middlewares/rfal/rfal_iso15693_2.d \
./Middlewares/rfal/rfal_isoDep.d \
./Middlewares/rfal/rfal_nfc.d \
./Middlewares/rfal/rfal_nfcDep.d \
./Middlewares/rfal/rfal_nfca.d \
./Middlewares/rfal/rfal_nfcb.d \
./Middlewares/rfal/rfal_nfcf.d \
./Middlewares/rfal/rfal_nfcv.d \
./Middlewares/rfal/rfal_st25tb.d \
./Middlewares/rfal/rfal_st25xv.d \
./Middlewares/rfal/rfal_t1t.d \
./Middlewares/rfal/rfal_t2t.d \
./Middlewares/rfal/rfal_t4t.d 

OBJS += \
./Middlewares/rfal/rfal_analogConfig.o \
./Middlewares/rfal/rfal_cd.o \
./Middlewares/rfal/rfal_crc.o \
./Middlewares/rfal/rfal_dpo.o \
./Middlewares/rfal/rfal_iso15693_2.o \
./Middlewares/rfal/rfal_isoDep.o \
./Middlewares/rfal/rfal_nfc.o \
./Middlewares/rfal/rfal_nfcDep.o \
./Middlewares/rfal/rfal_nfca.o \
./Middlewares/rfal/rfal_nfcb.o \
./Middlewares/rfal/rfal_nfcf.o \
./Middlewares/rfal/rfal_nfcv.o \
./Middlewares/rfal/rfal_st25tb.o \
./Middlewares/rfal/rfal_st25xv.o \
./Middlewares/rfal/rfal_t1t.o \
./Middlewares/rfal/rfal_t2t.o \
./Middlewares/rfal/rfal_t4t.o 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/rfal/rfal_analogConfig.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_analogConfig.c Middlewares/rfal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/rfal/rfal_cd.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_cd.c Middlewares/rfal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/rfal/rfal_crc.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_crc.c Middlewares/rfal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/rfal/rfal_dpo.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_dpo.c Middlewares/rfal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/rfal/rfal_iso15693_2.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_iso15693_2.c Middlewares/rfal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/rfal/rfal_isoDep.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_isoDep.c Middlewares/rfal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/rfal/rfal_nfc.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_nfc.c Middlewares/rfal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/rfal/rfal_nfcDep.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_nfcDep.c Middlewares/rfal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/rfal/rfal_nfca.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_nfca.c Middlewares/rfal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/rfal/rfal_nfcb.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_nfcb.c Middlewares/rfal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/rfal/rfal_nfcf.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_nfcf.c Middlewares/rfal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/rfal/rfal_nfcv.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_nfcv.c Middlewares/rfal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/rfal/rfal_st25tb.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_st25tb.c Middlewares/rfal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/rfal/rfal_st25xv.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_st25xv.c Middlewares/rfal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/rfal/rfal_t1t.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_t1t.c Middlewares/rfal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/rfal/rfal_t2t.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_t2t.c Middlewares/rfal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/rfal/rfal_t4t.o: C:/TouchGFXProjects/StockManagement_App2_FIXED_OldGraphics/StockManagement_App2_FIXED_OldGraphics/Middlewares_patch/rfal/Src/rfal_t4t.c Middlewares/rfal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -DST25R3916B -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Drivers/BSP -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I../../X-CUBE-SUBG2/Target -I../../X-CUBE-SUBG2/App -I../../X-CUBE-NFC6/Target -I../../X-CUBE-NFC6/App -I../../Drivers/BSP/S2868A1 -I../../Drivers/BSP/Components/ST25R3916 -I../../Drivers/BSP/Components/S2LP -I../../Drivers/BSP/Components/S2LP/S2LP_Library/inc -I../../Middlewares_patch/rfal/Src -I../../Middlewares_patch/rfal/Inc -I../../Middlewares_patch/ndef/Inc/poller -I../../Middlewares_patch/ndef/Inc/message -I../../Middlewares_patch/ndef/Inc -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares_patch/ST/touchgfx_components/gpu2d/TouchGFXNema/include -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-rfal

clean-Middlewares-2f-rfal:
	-$(RM) ./Middlewares/rfal/rfal_analogConfig.cyclo ./Middlewares/rfal/rfal_analogConfig.d ./Middlewares/rfal/rfal_analogConfig.o ./Middlewares/rfal/rfal_analogConfig.su ./Middlewares/rfal/rfal_cd.cyclo ./Middlewares/rfal/rfal_cd.d ./Middlewares/rfal/rfal_cd.o ./Middlewares/rfal/rfal_cd.su ./Middlewares/rfal/rfal_crc.cyclo ./Middlewares/rfal/rfal_crc.d ./Middlewares/rfal/rfal_crc.o ./Middlewares/rfal/rfal_crc.su ./Middlewares/rfal/rfal_dpo.cyclo ./Middlewares/rfal/rfal_dpo.d ./Middlewares/rfal/rfal_dpo.o ./Middlewares/rfal/rfal_dpo.su ./Middlewares/rfal/rfal_iso15693_2.cyclo ./Middlewares/rfal/rfal_iso15693_2.d ./Middlewares/rfal/rfal_iso15693_2.o ./Middlewares/rfal/rfal_iso15693_2.su ./Middlewares/rfal/rfal_isoDep.cyclo ./Middlewares/rfal/rfal_isoDep.d ./Middlewares/rfal/rfal_isoDep.o ./Middlewares/rfal/rfal_isoDep.su ./Middlewares/rfal/rfal_nfc.cyclo ./Middlewares/rfal/rfal_nfc.d ./Middlewares/rfal/rfal_nfc.o ./Middlewares/rfal/rfal_nfc.su ./Middlewares/rfal/rfal_nfcDep.cyclo ./Middlewares/rfal/rfal_nfcDep.d ./Middlewares/rfal/rfal_nfcDep.o ./Middlewares/rfal/rfal_nfcDep.su ./Middlewares/rfal/rfal_nfca.cyclo ./Middlewares/rfal/rfal_nfca.d ./Middlewares/rfal/rfal_nfca.o ./Middlewares/rfal/rfal_nfca.su ./Middlewares/rfal/rfal_nfcb.cyclo ./Middlewares/rfal/rfal_nfcb.d ./Middlewares/rfal/rfal_nfcb.o ./Middlewares/rfal/rfal_nfcb.su ./Middlewares/rfal/rfal_nfcf.cyclo ./Middlewares/rfal/rfal_nfcf.d ./Middlewares/rfal/rfal_nfcf.o ./Middlewares/rfal/rfal_nfcf.su ./Middlewares/rfal/rfal_nfcv.cyclo ./Middlewares/rfal/rfal_nfcv.d ./Middlewares/rfal/rfal_nfcv.o ./Middlewares/rfal/rfal_nfcv.su ./Middlewares/rfal/rfal_st25tb.cyclo ./Middlewares/rfal/rfal_st25tb.d ./Middlewares/rfal/rfal_st25tb.o ./Middlewares/rfal/rfal_st25tb.su ./Middlewares/rfal/rfal_st25xv.cyclo ./Middlewares/rfal/rfal_st25xv.d ./Middlewares/rfal/rfal_st25xv.o ./Middlewares/rfal/rfal_st25xv.su ./Middlewares/rfal/rfal_t1t.cyclo ./Middlewares/rfal/rfal_t1t.d ./Middlewares/rfal/rfal_t1t.o ./Middlewares/rfal/rfal_t1t.su ./Middlewares/rfal/rfal_t2t.cyclo ./Middlewares/rfal/rfal_t2t.d ./Middlewares/rfal/rfal_t2t.o ./Middlewares/rfal/rfal_t2t.su ./Middlewares/rfal/rfal_t4t.cyclo ./Middlewares/rfal/rfal_t4t.d ./Middlewares/rfal/rfal_t4t.o ./Middlewares/rfal/rfal_t4t.su

.PHONY: clean-Middlewares-2f-rfal

